import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { ApolloClient, InMemoryCache, gql } from "@apollo/client";
import { formatDistanceToNow } from "date-fns";

export const getServerSideProps = async () => {
  const client = new ApolloClient({
    uri: "https://api.spacex.land/graphql/",
    cache: new InMemoryCache(),
  });

  const { data } = await client.query({
    query: gql`
      query getLastLauches {
        launchesPast(limit: 10) {
          id
          mission_name
          launch_date_local
          rocket {
            rocket_name
          }
          links {
            video_link
          }
        }
      }
    `,
  });

  return {
    props: {
      launches: data.launchesPast,
    },
  };
};

export default function Launches({ launches }) {
  console.log(launches);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>SpaceX Launches</h1>

        <p className={styles.description}>View the last SpaceX launches</p>

        <div className={styles.grid}>
          {launches.map((launch) => (
            <a
              key={launch.id}
              href={launch.links.video_link}
              className={styles.card}
            >
              <h2>{launch.mission_name}</h2>
              <p>
                <strong>Date: </strong>
                {formatDistanceToNow(new Date(launch.launch_date_local), {
                  addSuffix: true,
                })}
              </p>
              <p>
                <strong>Rocket: </strong>
                {launch.rocket.rocket_name}
              </p>
            </a>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
